name: Unity CI/CD with Parallel Tests and Build

on: [workflow_dispatch, push] # Added workflow_dispatch for manual runs

jobs:
  test:
    name: Run tests 🧪
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          # Add other test runner params here if needed, e.g., unityVersion, testMode

  build:
    name: Build project ✨
    runs-on: ubuntu-latest
    needs: test # This ensures the build job only runs if the test job completes successfully
    permissions:
      checks: write
      contents: write # Needed for uploading artifacts and potentially for releases
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      # --- Debugging step: Show all uncommitted changes (diff) ---
      # This is placed before the build step to catch any modifications
      # made by previous actions or Unity's internal processes.
      - name: Show all uncommitted changes (diff)
        run: |
          echo "--- Checking for all uncommitted changes ---"
          if git diff --quiet HEAD; then
            echo "No uncommitted changes found."
          else
            echo "Uncommitted changes detected:"
            git diff HEAD
            # Optionally, uncomment 'exit 1' if you want the workflow to fail here
            # if unexpected changes are found.
            # exit 1
          fi
          echo "--- End of uncommitted changes diff ---"
        continue-on-error: true # Set to false if you want the workflow to fail on diffs

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows # Used your original targetPlatform
          # allowDirtyBuild: true # Not recommended

      - name: Upload build artifact
        uses: actions/upload-artifact@v4 # Updated to v4
        with:
          name: Build
          path: build
          retention-days: 7 # Auto-delete after 1 week
