name: Friday Nightly Development Test/Build

on:
  workflow_dispatch:
  schedule:
    - cron: '59 23 * * 5' # Runs at 23:59 (11:59 PM) every Friday

jobs:
  test:
    name: Run tests 🧪
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Run tests
        uses: game-ci/unity-test-runner@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: Build project ✨
    runs-on: ubuntu-latest
    needs: test
    permissions:
      checks: write
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Cache Unity Library
        uses: actions/cache@v3
        with:
          path: Library
          key: Library-${{ hashFiles('Assets/**', 'Packages/**', 'ProjectSettings/**') }}
          restore-keys: |
            Library-

      - name: Show all uncommitted changes (diff)
        run: |
          echo "--- Checking for all uncommitted changes ---"
          if git diff --quiet HEAD; then
            echo "No uncommitted changes found."
          else
            echo "Uncommitted changes detected:"
            git diff HEAD
          fi
          echo "--- End of uncommitted changes diff ---"
        continue-on-error: true

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: StandaloneWindows
          buildOptions: Development

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: Build
          path: build
          retention-days: 7
